#@name get-prompts
GET http://localhost:3333/prompts

###

#@name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

#@name create-transcription
POST http://localhost:3333/videos/aca2e652-7b00-400f-a0c4-2c4ae145d6f7/transcription
Content-Type: application/json

{
    "prompt": "ring"
}
###

#@name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "aca2e652-7b00-400f-a0c4-2c4ae145d6f7",
    "prompt": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}'''",
    "temperature": 0.5
}